name: HyperCloud
include:
  - app/addons/addons.yml
packages:
  BareKit:
    url: https://github.com/holepunchto/bare-kit-swift
    branch: main
  BareRPC:
    url: https://github.com/holepunchto/bare-rpc-swift
    branch: main
targets:
  App:
    type: application
    supportedDestinations: [iOS, macOS]
    deploymentTarget:
      iOS: "16.0"
      macOS: "11.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: to.holepunch.bare.ios
        SWIFT_VERSION: 5.0
      configs:
        Debug:
          CODE_SIGN_IDENTITY: '-'
          CODE_SIGN_STYLE: Automatic
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGNING_ALLOWED: NO
          VALIDATE_PRODUCT: NO
          VALIDATE_WORKSPACE: NO
          OTHER_CODE_SIGN_FLAGS: '--deep --no-strict'
        Release:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: 'Apple Development'
          CODE_SIGNING_REQUIRED: YES
          VALIDATE_PRODUCT: YES
    info:
      path: app/Info.plist
    entitlements:
      path: app/App.entitlements
      properties:
        # aps-environment: development
        # com.apple.security.application-groups:
          # - group.to.holepunch.bare.ios
        com.apple.security.cs.allow-jit: true
    dependencies:
      - framework: app/frameworks/BareKit.xcframework
      - package: BareKit
      - package: BareRPC
      # - target: NotificationServiceExtension
    sources:
      - path: app/App.swift
      - path: app/app.js
      - path: app/app.bundle
        optional: true

      - path: app/commands.js
      - path: app/store.js
      - path: app/space.js

      - path: app/Cmd.swift
      - path: app/NewSpaceView.swift
      - path: app/SpaceDetailView.swift
      - path: app/MenuBarView.swift
      - path: app/Worker+Events.swift
      - path: app/Worker.swift
      - path: app/IPCBridge.swift
      - path: app/Space.swift
      - path: app/SpacesListView.swift


    scheme:
      preActions:
        - name: Link
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-link" \
              --host darwin-arm64 \
              --host ios-arm64 \
              --host ios-arm64-simulator \
              --out ${PWD}/app/addons \
              ${PWD}
        - name: Pack
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --host darwin-arm64 \
              --host ios-arm64 \
              --host ios-arm64-simulator \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app/app.bundle \
              ${PWD}/app/app.js


